# Generated by Django 5.1.7 on 2025-04-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_shippingaddress_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Town',
            new_name='town',
        ),
    ]
