# Generated by Django 5.1.7 on 2025-05-02 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_brandingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingrequest',
            name='branding_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='BrandingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='branding_uploads/')),
                ('branding_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.brandingrequest')),
            ],
        ),
    ]
