# Generated by Django 5.1.7 on 2025-05-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_orderid_alter_order_shippingaddress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deleveredAt',
            new_name='deliveredAt',
        ),
    ]
