# Generated by Django 5.1.7 on 2025-08-06 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentwebhook',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='api.payment'),
        ),
    ]
