# Generated by Django 5.1.7 on 2025-08-07 07:20

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_payment_api_payment_referen_789c98_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='sliderdata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sliderdata/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=None, default='avatar.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 300], upload_to='avatar/'),
        ),
    ]
