# Generated by Django 6.0 on 2025-12-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_product_image_alter_sliderdata_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="categories",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="categories",
            name="slug",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
