name: Deploy to Linode Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH & Deploy
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/ivano/ausar2
            git pull origin main

            # Activate virtualenv
            source /home/ivano/ausar2/venv/bin/activate

            # Backend setup
            cd backend
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput

            # Frontend build
            cd ../frontend
            npm install
            npm run build

            # Restart gunicorn (make sure passwordless sudo is configured)
            sudo systemctl restart gunicorn
          EOF
          
